In [33]:
import pandas as pd
import numpy as np
import glob

In [34]:
#filter for only filenames that have digits before the .csv
fuel_datasets_dir='/home/sam/Github Folder/FuelCheck/*[0-9]*.csv'

In [35]:
#generate a list of filenames
l=[l for l in glob.glob(fuel_datasets_dir)]

In [36]:
#run a for loop to get all the files into pandas
fuel_list=[]
for i in l:
    fuel_list.append(pd.read_csv(i))

In [37]:
#not sure if i will need this, just stripped the month and year, to add 
#to the fuel_table as an index
j=[j.split('/')[-1].lower().rstrip('.csv') for j in l]

In [38]:
#concatenate all the files into one table
fuel_table=pd.concat(fuel_list, sort=True)

In [39]:
#an irrelevant column, as such i dropped it
fuel_table = fuel_table.drop(columns='Unnamed: 0')

In [40]:
fuel_table.head(3)
#fueltype vs fuelcode??

,Address,Brand,FuelCode,FuelType,Postcode,Price,PriceUpdatedDate,ServiceStationName,Suburb
0,"2355 Camden Valley Way (Corner Beech Road), Ca...",7-Eleven,U91,NaN,2170.0,107.7,2017-04-01 00:24:42,7-Eleven Casula,Casula
1,"2355 Camden Valley Way (Corner Beech Road), Ca...",7-Eleven,P98,NaN,2170.0,123.7,2017-04-01 00:24:42,7-Eleven Casula,Casula
2,"2355 Camden Valley Way (Corner Beech Road), Ca...",7-Eleven,E10,NaN,2170.0,105.7,2017-04-01 00:24:42,7-Eleven Casula,Casula

In [41]:
fuel_table[fuel_table['FuelType'].notnull()]
#fuelcode and fueltype mean the same thing ... i'll merge them

,Address,Brand,FuelCode,FuelType,Postcode,Price,PriceUpdatedDate,ServiceStationName,Suburb
0,"531 - 537 Glebe Road & Bryant Street, Adamstow...",7-Eleven,NaN,E10,2289.0,105.9,2016-08-02 06:21:05.090,7-Eleven Adamstown,Adamstown
1,"531 - 537 Glebe Road & Bryant Street, Adamstow...",7-Eleven,NaN,E10,2289.0,103.9,2016-08-05 04:09:25.317,7-Eleven Adamstown,Adamstown
2,"531 - 537 Glebe Road & Bryant Street, Adamstow...",7-Eleven,NaN,E10,2289.0,102.9,2016-08-08 09:08:40.420,7-Eleven Adamstown,Adamstown
3,"531 - 537 Glebe Road & Bryant Street, Adamstow...",7-Eleven,NaN,E10,2289.0,101.9,2016-08-09 21:04:51.343,7-Eleven Adamstown,Adamstown
4,"531 - 537 Glebe Road & Bryant Street, Adamstow...",7-Eleven,NaN,E10,2289.0,99.9,2016-08-17 03:23:15.013,7-Eleven Adamstown,Adamstown
5,"531 - 537 Glebe Road & Bryant Street, Adamstow...",7-Eleven,NaN,E10,2289.0,96.9,2016-08-18 03:32:50.887,7-Eleven Adamstown,Adamstown
6,"531 - 537 Glebe Road & Bryant Street, Adamstow...",7-Eleven,NaN,LPG,2289.0,61.9,2016-08-17 07:57:11.597,7-Eleven Adamstown,Adamstown
7,"531 - 537 Glebe Road & Bryant Street, Adamstow...",7-Eleven,NaN,P95,2289.0,118.9,2016-08-02 06:21:05.090,7-Eleven Adamstown,Adamstown
8,"531 - 537 Glebe Road & Bryant Street, Adamstow...",7-Eleven,NaN,P95,2289.0,116.9,2016-08-05 04:09:25.317,7-Eleven Adamstown,Adamstown
9,"531 - 537 Glebe Road & Bryant Street, Adamstow...",7-Eleven,NaN,P95,2289.0,115.9,2016-08-08 09:08:40.420,7-Eleven Adamstown,Adamstown
10,"531 - 537 Glebe Road & Bryant Street, Adamstow...",7-Eleven,NaN,P95,2289.0,114.9,2016-08-09 21:04:51.343,7-Eleven Adamstown,Adamstown
11,"531 - 537 Glebe Road & Bryant Street, Adamstow...",7-Eleven,NaN,P95,2289.0,112.9,2016-08-17 03:23:15.013,7-Eleven Adamstown,Adamstown
12,"531 - 537 Glebe Road & Bryant Street, Adamstow...",7-Eleven,NaN,P95,2289.0,109.9,2016-08-18 03:32:50.887,7-Eleven Adamstown,Adamstown
13,"531 - 537 Glebe Road & Bryant Street, Adamstow...",7-Eleven,NaN,P98,2289.0,123.9,2016-08-02 06:21:05.090,7-Eleven Adamstown,Adamstown
14,"531 - 537 Glebe Road & Bryant Street, Adamstow...",7-Eleven,NaN,P98,2289.0,121.9,2016-08-05 04:09:25.317,7-Eleven Adamstown,Adamstown
15,"531 - 537 Glebe Road & Bryant Street, Adamstow...",7-Eleven,NaN,P98,2289.0,120.9,2016-08-08 09:08:40.420,7-Eleven Adamstown,Adamstown
16,"531 - 537 Glebe Road & Bryant Street, Adamstow...",7-Eleven,NaN,P98,2289.0,119.9,2016-08-09 21:04:51.343,7-Eleven Adamstown,Adamstown
17,"531 - 537 Glebe Road & Bryant Street, Adamstow...",7-Eleven,NaN,P98,2289.0,117.9,2016-08-17 03:23:15.013,7-Eleven Adamstown,Adamstown
18,"531 - 537 Glebe Road & Bryant Street, Adamstow...",7-Eleven,NaN,P98,2289.0,114.9,2016-08-18 03:32:50.887,7-Eleven Adamstown,Adamstown
19,"531 - 537 Glebe Road & Bryant Street, Adamstow...",7-Eleven,NaN,PDL,2289.0,117.9,2016-08-08 02:12:28.613,7-Eleven Adamstown,Adamstown
20,"531 - 537 Glebe Road & Bryant Street, Adamstow...",7-Eleven,NaN,PDL,2289.0,115.9,2016-08-17 07:57:11.597,7-Eleven Adamstown,Adamstown
21,"531 - 537 Glebe Road & Bryant Street, Adamstow...",7-Eleven,NaN,PDL,2289.0,114.9,2016-08-24 04:18:57.660,7-Eleven Adamstown,Adamstown
22,"531 - 537 Glebe Road & Bryant Street, Adamstow...",7-Eleven,NaN,PDL,2289.0,112.9,2016-08-25 00:15:56.587,7-Eleven Adamstown,Adamstown
23,"531 - 537 Glebe Road & Bryant Street, Adamstow...",7-Eleven,NaN,U91,2289.0,107.9,2016-08-02 06:21:05.090,7-Eleven Adamstown,Adamstown
24,"531 - 537 Glebe Road & Bryant Street, Adamstow...",7-Eleven,NaN,U91,2289.0,105.9,2016-08-05 04:09:25.317,7-Eleven Adamstown,Adamstown
25,"531 - 537 Glebe Road & Bryant Street, Adamstow...",7-Eleven,NaN,U91,2289.0,104.9,2016-08-08 09:08:40.420,7-Eleven Adamstown,Adamstown
26,"531 - 537 Glebe Road & Bryant Street, Adamstow...",7-Eleven,NaN,U91,2289.0,103.9,2016-08-09 21:04:51.343,7-Eleven Adamstown,Adamstown
27,"531 - 537 Glebe Road & Bryant Street, Adamstow...",7-Eleven,NaN,U91,2289.0,101.9,2016-08-17 03:23:15.013,7-Eleven Adamstown,Adamstown
28,"531 - 537 Glebe Road & Bryant Street, Adamstow...",7-Eleven,NaN,U91,2289.0,98.9,2016-08-18 03:32:50.887,7-Eleven Adamstown,Adamstown
29,"138-142 Princes Highway, ALBION PARK RAIL NSW ...",7-Eleven,NaN,E10,2527.0,98.2,2016-08-01 00:25:58.010,7-Eleven Albion Park Rail,ALBION PARK RAIL
...,...,...,...,...,...,...,...,...,...
74349,"449 Captain Cook Drive, Woolooware NSW 2230",Caltex Woolworths,NaN,P98,2230.0,130.4,2016-08-29 08:42:11.257,Woolworths Woolooware,Woolooware
74350,"449 Captain Cook Drive, Woolooware NSW 2230",Caltex Woolworths,NaN,P98,2230.0,128.9,2016-08-29 21:57:22.357,Woolworths Woolooware,Woolooware
74351,"449 Captain Cook Drive, Woolooware NSW 2230",Caltex Woolworths,NaN,P98,2230.0,125.9,2016-08-30 23:58:41.820,Woolworths Woolooware,Woolooware
74352,"449 Captain Cook Drive, Woolooware NSW 2230",Caltex Woolworths,NaN,U91,2230.0,105.9,2016-08-01 19:16:48.637,Woolworths Woolooware,Woolooware
74353,"449 Captain Cook Drive, Woolooware NSW 2230",Caltex Woolworths,NaN,U91,2230.0,104.4,2016-08-02 20:34:45.703,Woolworths Woolooware,Woolooware
74354,"449 Captain Cook Drive, Woolooware NSW 2230",Caltex Woolworths,NaN,U91,2230.0,103.9,2016-08-03 09:15:38.317,Woolworths Woolooware,Woolooware
74355,"449 Captain Cook Drive, Woolooware NSW 2230",Caltex Woolworths,NaN,U91,2230.0,103.4,2016-08-04 02:00:03.993,Woolworths Woolooware,Woolooware
74356,"449 Captain Cook Drive, Woolooware NSW 2230",Caltex Woolworths,NaN,U91,2230.0,102.9,2016-08-05 02:31:11.513,Woolworths Woolooware,Woolooware
74357,"449 Captain Cook Drive, Woolooware NSW 2230",Caltex Woolworths,NaN,U91,2230.0,101.9,2016-08-05 21:17:52.990,Woolworths Woolooware,Woolooware
74358,"449 Captain Cook Drive, Woolooware NSW 2230",Caltex Woolworths,NaN,U91,2230.0,100.4,2016-08-08 01:02:13.623,Woolworths Woolooware,Woolooware
74359,"449 Captain Cook Drive, Woolooware NSW 2230",Caltex Woolworths,NaN,U91,2230.0,98.9,2016-08-08 03:19:28.723,Woolworths Woolooware,Woolooware
74360,"449 Captain Cook Drive, Woolooware NSW 2230",Caltex Woolworths,NaN,U91,2230.0,97.9,2016-08-11 00:33:44.400,Woolworths Woolooware,Woolooware
74361,"449 Captain Cook Drive, Woolooware NSW 2230",Caltex Woolworths,NaN,U91,2230.0,97.4,2016-08-11 20:32:01.730,Woolworths Woolooware,Woolooware
74362,"449 Captain Cook Drive, Woolooware NSW 2230",Caltex Woolworths,NaN,U91,2230.0,96.9,2016-08-14 02:59:49.553,Woolworths Woolooware,Woolooware
74363,"449 Captain Cook Drive, Woolooware NSW 2230",Caltex Woolworths,NaN,U91,2230.0,96.4,2016-08-15 01:02:17.117,Woolworths Woolooware,Woolooware
74364,"449 Captain Cook Drive, Woolooware NSW 2230",Caltex Woolworths,NaN,U91,2230.0,95.9,2016-08-17 00:16:13.710,Woolworths Woolooware,Woolooware
74365,"449 Captain Cook Drive, Woolooware NSW 2230",Caltex Woolworths,NaN,U91,2230.0,127.4,2016-08-17 07:30:21.037,Woolworths Woolooware,Woolooware
74366,"449 Captain Cook Drive, Woolooware NSW 2230",Caltex Woolworths,NaN,U91,2230.0,125.9,2016-08-20 09:20:40.450,Woolworths Woolooware,Woolooware
74367,"449 Captain Cook Drive, Woolooware NSW 2230",Caltex Woolworths,NaN,U91,2230.0,123.4,2016-08-23 00:19:41.607,Woolworths Woolooware,Woolooware
74368,"449 Captain Cook Drive, Woolooware NSW 2230",Caltex Woolworths,NaN,U91,2230.0,121.4,2016-08-23 08:05:20.447,Woolworths Woolooware,Woolooware
74369,"449 Captain Cook Drive, Woolooware NSW 2230",Caltex Woolworths,NaN,U91,2230.0,119.4,2016-08-23 23:03:03.627,Woolworths Woolooware,Woolooware
74370,"449 Captain Cook Drive, Woolooware NSW 2230",Caltex Woolworths,NaN,U91,2230.0,116.4,2016-08-25 23:02:26.477,Woolworths Woolooware,Woolooware
74371,"449 Captain Cook Drive, Woolooware NSW 2230",Caltex Woolworths,NaN,U91,2230.0,114.9,2016-08-26 01:19:22.643,Woolworths Woolooware,Woolooware
74372,"449 Captain Cook Drive, Woolooware NSW 2230",Caltex Woolworths,NaN,U91,2230.0,112.9,2016-08-26 21:33:32.300,Woolworths Woolooware,Woolooware
74373,"449 Captain Cook Drive, Woolooware NSW 2230",Caltex Woolworths,NaN,U91,2230.0,110.9,2016-08-27 01:48:51.440,Woolworths Woolooware,Woolooware
74374,"449 Captain Cook Drive, Woolooware NSW 2230",Caltex Woolworths,NaN,U91,2230.0,107.4,2016-08-30 23:58:41.820,Woolworths Woolooware,Woolooware
74375,"Cnr Lovell & Thornhill Sts, Young NSW 2594",Caltex Woolworths,NaN,DL,2594.0,105.9,2016-08-03 06:46:36.110,Woolworths Young,Young
74376,"Cnr Lovell & Thornhill Sts, Young NSW 2594",Caltex Woolworths,NaN,DL,2594.0,105.7,2016-08-04 01:31:28.110,Woolworths Young,Young
74377,"Cnr Lovell & Thornhill Sts, Young NSW 2594",Caltex Woolworths,NaN,E10,2594.0,106.9,2016-08-03 06:46:36.110,Woolworths Young,Young
74378,"Cnr Lovell & Thornhill Sts, Young NSW 2594",Caltex Woolworths,NaN,P95,2594.0,120.9,2016-08-03 06:46:36.110,Woolworths Young,Young

In [42]:
# 'merge' done
fuel_table['FuelCode']=np.where(fuel_table['FuelCode'].isnull(),fuel_table['FuelType'],fuel_table['FuelCode'])

In [43]:
#fueltype column removed
fuel_table.drop('FuelType',axis=1,inplace=True)

In [44]:
fuel_table.head(3)

,Address,Brand,FuelCode,Postcode,Price,PriceUpdatedDate,ServiceStationName,Suburb
0,"2355 Camden Valley Way (Corner Beech Road), Ca...",7-Eleven,U91,2170.0,107.7,2017-04-01 00:24:42,7-Eleven Casula,Casula
1,"2355 Camden Valley Way (Corner Beech Road), Ca...",7-Eleven,P98,2170.0,123.7,2017-04-01 00:24:42,7-Eleven Casula,Casula
2,"2355 Camden Valley Way (Corner Beech Road), Ca...",7-Eleven,E10,2170.0,105.7,2017-04-01 00:24:42,7-Eleven Casula,Casula

In [45]:
fuel_table.loc[fuel_table['Address'].isnull()] #null values to delete

,Address,Brand,FuelCode,Postcode,Price,PriceUpdatedDate,ServiceStationName,Suburb
5474,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24763,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35848,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46690,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71112,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
fuel_table.isnull().sum()

Address               6
Brand                 6
FuelCode              6
Postcode              6
Price                 6
PriceUpdatedDate      6
ServiceStationName    6
Suburb                6
dtype: int64

In [47]:
fuel_table.shape

(1775761, 8)

In [48]:
fuel_table.dropna(inplace=True,how='all')

In [49]:
fuel_table.shape

(1775755, 8)

In [50]:
fuel_table.isnull().sum()

Address               0
Brand                 0
FuelCode              0
Postcode              0
Price                 0
PriceUpdatedDate      0
ServiceStationName    0
Suburb                0
dtype: int64

In [51]:
fuel_table.head(3)

,Address,Brand,FuelCode,Postcode,Price,PriceUpdatedDate,ServiceStationName,Suburb
0,"2355 Camden Valley Way (Corner Beech Road), Ca...",7-Eleven,U91,2170.0,107.7,2017-04-01 00:24:42,7-Eleven Casula,Casula
1,"2355 Camden Valley Way (Corner Beech Road), Ca...",7-Eleven,P98,2170.0,123.7,2017-04-01 00:24:42,7-Eleven Casula,Casula
2,"2355 Camden Valley Way (Corner Beech Road), Ca...",7-Eleven,E10,2170.0,105.7,2017-04-01 00:24:42,7-Eleven Casula,Casula

In [52]:
fuel_table.to_csv('/home/sam/Desktop/data/FuelCheck/fuel_table.csv',index=None)